python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'beard' --lr 0.00001 --lambda_att 0.01 --iterations 10000
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'smile' --lr 0.00001 --lambda_att 0.01 --iterations 10000    
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'big nose' --lr 0.00001 --lambda_att 0.01 --iterations 10000                                                                                      
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'curly hair' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'open mouth' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'closed mouth' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'moustache' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'big eyes' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'bald-headed' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'long hair' --lr 0.00001 --lambda_att 0.01 --iterations 10000                   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'short hair' --lr 0.00001 --lambda_att 0.01 --iterations 10000   
python train_FEAT.py --batch_size 2 --stylegan2_ckpt checkpoint/stylegan2-ffhq-config-f.pt --truncation 0.9 --clip_text 'surprised' --lr 0.00001 --lambda_att 0.01 --iterations 10000   